apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: prometheus-grafana-rules
  namespace: monitoring
spec:
  groups:
  - name: KubeGrafanaMonitoring
    rules:
    - alert: KubeGrafanaDown 
      annotations:
        detail:  "你的监控展示平台Down掉了，请确认信息，IP：{{$labels.instance}}, POD：{{$labels.pod}}，(当前值: {{ $value }})"
        summary: "{{$labels.instance}}: Kubelet Down"
      expr: |
        up{endpoint="http",job="grafana",namespace="monitoring",service="grafana"} == 0
      for: 1m
      labels:
        severity: 警告